### ISSUE TITLE
Add BIS and CBA functions to new auto-completion

### ISSUE THREAD

**Issue by jonpas** [acemod/language-arma-atom#18]
Required for 2.0.0.
- [x] BIS #40 
- [x] CBA #27

**Comment by jonpas** [comment]
BIS functions are in most part done with `armadoc.py`, just need to change page title. Problem is that many functions have direct header as a wiki page (not same format as script commands and other functions - [example](https://community.bistudio.com/wiki/BIS_fnc_getServerVariable)). This will need some adjustment.

CBA functions can be taken directly from https://dev.withsix.com/docs/cba/index/Functions.html
CBA macros can also be made automatic from https://dev.withsix.com/docs/cba/index/Macros.html

**Comment by jonpas** [comment]
@simon84 Have you already started work on BIS functions by any chance? No rush, just asking so we don't work on the same thing.

**Comment by simon84** [comment]
No, did not find time to do it.

**Comment by jonpas** [comment]
Thanks to @Cuel this is done.
