### ISSUE TITLE
Verify which macros are ACE3's and which CBA's

### ISSUE THREAD

**Issue by jonpas** [acemod/language-arma-atom#19]
Currently it's **not** correct.

**Comment by kymckay** [comment]
Aren't they all CBA's? :stuck_out_tongue:

**Comment by jokoho48** [comment]
No
This are the ACE Macros 
https://github.com/acemod/ACE3/blob/master/addons/main/script_debug.hpp
https://github.com/acemod/ACE3/blob/master/addons/main/script_macros.hpp

**Comment by jonpas** [comment]
@SilentSpike No, ACE3 has a lot of new ones that CBA hasn't, mostly debug ones and external variants. (I'd say it wouldn't be bad to port them back to CBA btw.)
