### ISSUE TITLE
Preprocessor definitions don't auto-complete

### ISSUE THREAD

**Issue by jonpas** [acemod/language-arma-atom#24]
```
"#include",
"#define",
"#undef",
"#ifdef",
"#endif"
```

**Comment by thojkooi** [comment]
We could remove the `#` ? Or we can make them into snippets?

**Comment by jonpas** [comment]
I am pretty sure we can somehow escape `#` so it won't block auto-completion, anything starting with it won't pop-up. Snippet would work but then it gets confusing, best would be if typing `#` would just pop-up pre-processor definitions.
