### ISSUE TITLE
#define autocompletition adds second #

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/language-arma-atom#43]
Typing `#def` and then pressing tab to autocomplete results in `##define keyword value`.

**Comment by jonpas** [comment]
That is because the match pattern is `define` without leading hashtag, Atom for some reason doesn't support it, they might have fixed it since then though or there could be another way.

**Comment by jonpas** [comment]
@BaerMitUmlaut what would we wanted behaviour? You type `#de` (for example) and output is `#define` or you type `def` (for example) and output is `#define`? I see in C++ it seems to be that you type it without the leading hashtag and autocompletes adds it.

**Comment by simon84** [comment]
Any progress in this discussion? For me its only a matter of taste and not a bug.

**Comment by thojkooi** [comment]
I'd go with the C++ style for this. So nothing would change.

**Comment by jonpas** [comment]
Same here, closing then.
