### ISSUE TITLE
Arma config: String doesn't close if last character is backslash

### ISSUE THREAD

**Issue by VKing6** [acemod/language-arma-atom#49]
Related to the backslash character causing following letters in config strings to be highlighted, if the last character in a string is a backslash (e.g. "Something\fnord\") the string highlighting won't end until the next quote mark in the file.

[Picture](http://i.imgur.com/6cildsP.png)

**Comment by simon84** [comment]
That's because we are using the cpp syntax highlighting for the arms config language. We should consider to define an own language definition for the arms config.

**Comment by jokoho48** [comment]
the main config file must named config.cpp @simon84

**Comment by simon84** [comment]
Of course. Then you have to change the syntax highlighting manually. But we cannot use the standard cpp syntax highlighter for config files, since the syntax is slightly different.

**Comment by kymckay** [comment]
Yeah I think I only first used the cpp syntax as a quick solution since it's mostly the same

**Comment by kymckay** [comment]
I think it's possible to continue to use it and override certain parts

**Comment by simon84** [comment]
Good idea. String definition in this case.

**Comment by jonpas** [comment]
I prefer changing what we need changed, since most of CPP's highlighting is exactly the same.

**Comment by jonpas** [comment]
Fixed by #50
