### ISSUE TITLE
missing command in

### ISSUE THREAD

**Issue by jokoho48** [acemod/language-arma-atom#53]
command in is missing in syntax Highlight

**Comment by jonpas** [comment]
Syntax highlighting only or auto-completion as well?

**Comment by simon84** [comment]
I have the in command as well as the for command on a blacklist in my command grabber script. Unfortunately these commands has disambiguity site in the wiki, which I am not able to parse at the moment. But I have an idea for a workaround. As soon as possible, I will commit changes regarding this issue.

**Comment by jonpas** [comment]
:+1:

**Comment by jonpas** [comment]
Fixed by #55
