### ISSUE TITLE
Missing command: ropeDetach

### ISSUE THREAD

**Issue by BaerMitUmlaut** [acemod/language-arma-atom#54]
ropeDetach does not get highlighted correctly.
https://community.bistudio.com/wiki/ropeDetach

**Comment by jonpas** [comment]
Auto-completion works fine?

**Comment by BaerMitUmlaut** [comment]
Nope, doesn't show up there either.

**Comment by simon84** [comment]
Ok, I have the bug. I'm searching for all commands in "Category:Scripting Commands Arma 3" in the wiki. But this command is found in "Category:Scripting Commands". So I will change this in my script. But than we have also depricated commands.

**Comment by jonpas** [comment]
I think having deprecated commands is fine, as long as they still work, it should be up to the user to use them or not use them. For any that don't work anymore we can add a blacklist, preferably in a separate file maybe which your Python script can read and then ignore? That would be helpful, I think it's better to blacklist things than add them manually after-all.

**Comment by jonpas** [comment]
Fixed by #55
