### ISSUE TITLE
Much code in one String doesn't show properly

### ISSUE THREAD

**Issue by unknownp** [acemod/language-arma-atom#57]
Hey,
If I use this on an Arma script that has for example a big string like:

_bigstring = "
    much here, like 100 lines or more
";
call compile _bigstring;

then you would see everything just in "green" as it is all part of "that" string :-/

**Comment by jokoho48** [comment]
i am not 100% sure but this can be a issue from Atom. i rember see this in C# and c++ and CS Code too

**Comment by unknownp** [comment]
mhh that might be true. Atom pretty much remembers me of Sublime, not sure why but it does. Well on Sublime I experienced the same problem

**Comment by thojkooi** [comment]
That's because it's a string. Why is this an issue? Or am I misunderstanding it here?

**Comment by jonpas** [comment]
Code in a string won't be highlighted as code pieces, but as one big string, is this not expected behaviour?

**Comment by unknownp** [comment]
Well in other programs like notepad++ or programmer's notepad it is not like that
You would only have the line where the string opens highlighted and where it ends

_test = "  <- this line

much code within a string

"; <- and this line

that way you can see as well from where to where the string goes but you also have good highlights on what's happening within

**Comment by kymckay** [comment]
First off I would simply recommend not having 100 lines of code in the form of a string :stuck_out_tongue:

Secondly, isn't this default behaviour in most text editors? I feel like last time I used N++ it behaved this way. Not sure there's even anything we can do about it, sounds more like a complaint with regard to Atom.

**Comment by unknownp** [comment]
Well in arma strings use way less memory than for example code.
Especially when it comes to networking in arma, sending code from client to server, server to client or client to client it makes a huge difference if you do that as a String (string is just much faster, even if you have to call compile it afterwards) or as Array, Scalar, Code

on N++ it is fine, I just wish it was like it is there, on this. As ATOM really seems to be nice :)

**Comment by thojkooi** [comment]
I do not consider this a bug, sorry.

**Comment by jonpas** [comment]
Same, it's expected behaviour (it even works like that in Visual Studio IIRC). Marking as invalid, if you'd like different behaviour it is something Atom  itself has to do.
