### ISSUE TITLE
isEqualTo is a Operator but dont have a Color Coding

### ISSUE THREAD

**Issue by jokoho48** [acemod/language-arma-atom#65]
isEqualTo dont have a Color Coding but other isEqualX

**Comment by jonpas** [comment]
Tagging #31 

I am not sure, `isEqualTo` directly compares just like `==` (but with obvious other differences), white other `isEqualTypeX` compare to a type or types, and is therefore a command.

I'd say leave as is.

**Comment by jonpas** [comment]
No input for over a month, closing as by design.
