### ISSUE TITLE
code autocomplete doesnt work right

### ISSUE THREAD

**Issue by ghost** [acemod/language-arma-atom#66]
how it should look like: 
https://i.gyazo.com/412e1599a952dd68ce41cc318183bff3.png

how i looks like: 
https://i.gyazo.com/bc4ba1def4dcc82f12b600762ca3ffc6.png

the autocomplete-window doesnt show the right commands, just commands that have the same letters in them. example shows that the actual typed command is the last item in the list, even tho it should be first

**Comment by jokoho48** [comment]
yeah i notice this too but i am not sure if this a Atom fault. because it's occluded on my Atom after the last Large Update.

**Comment by jonpas** [comment]
This is a bug in Atom, it appears the new prediction tech is a bit wonky. Nothing we can do either way.
