### ISSUE TITLE
Request: Make ACE and CBA optional

### ISSUE THREAD

**Issue by publicJorn** [acemod/language-arma-atom#67]
Hi, I thought it'd be user-friendly to be able to "uncheck" ACE and CBA support from the package settings.
This way, for the average mission scripter (non-ace non-plugins) there would be less matches for the autocomplete and snippets functions in SQF scope.

I made a fork and tried to figure this out myself, but I bumped into 2 obstacles:
1) it seems "snippets" and "settings" (subfolders) are autmatically loaded
2) I can't find any documentation on the "settings" folder being auto-loaded (assuming this is [Provider-API](https://github.com/atom/autocomplete-plus/wiki/Provider-API) functionality).

I have [this outstanding question](http://stackoverflow.com/questions/37249139/atom-package-optionally-load-snippet-file) on stackoverflow, to see if it's at all possible to exclude snippet files from the snippet folder. Or maybe some of you already know how this can be done..

**Comment by jonpas** [comment]
I was  thinking about it and came to the same issue, but I haven't looked deep into it yet.

**Comment by thojkooi** [comment]
I like this request. Lets see if we can come up with something for this @jonpas

**Comment by publicJorn** [comment]
I dove into the atom source and it seems there's no hook to optionally load snippets. See [https://github.com/atom/snippets/blob/master/lib/snippets.coffee#L81]() 

I couldn't find the source that loads the commands from the "settings" folder, but it probably works somewhat the same. 

The only way I can think of, is pitting the "optional" files in a separate folder and copying them when the support option is checked in settings. 

I have no previous atom hacking experience, but wouldn't mind giving it a go

**Comment by jonpas** [comment]
If you'd like, go ahead, we'd be happy to review it if and when you make a pull request. :smiley: 
It's a neat idea as well.

**Comment by publicJorn** [comment]
Well this was a small project of firsts :)
New to atom hacking, coffeescript and contributing to an open source project. Hope I created the [pull request](https://github.com/acemod/language-arma-atom/pull/68) properly.

**Comment by nicolasbadano** [comment]
Closed through #68
