### ISSUE TITLE
Wrong definition for (Q)PATHTOEF

### ISSUE THREAD

**Issue by dedmen** [acemod/language-arma-atom#78]
QPATHTOEF is defined as
`#define QPATHTOEF(var1,var2) QUOTE(PATHTOEF(var1,var2))`
but in atom it shows as the same as QPATHTOF which only has 1 arg.

**Comment by jonpas** [comment]
Problematic line: https://github.com/acemod/language-arma-atom/blob/12de7db7871a1ae55476e28a65d2d32752f86e60/settingsAvailable/language-sqf-macros-cba.json#L105

```
"snippet": "QPATHTOEF(${1:path})$0",
```

has to be changed to

```
"snippet": "QPATHTOEF(${1:component},${2:path})$0",
```

Same thing for `PATHTOEF` at https://github.com/acemod/language-arma-atom/blob/12de7db7871a1ae55476e28a65d2d32752f86e60/settingsAvailable/language-sqf-macros-cba.json#L95
