### ISSUE TITLE
CBA_Settings functions missing

### ISSUE THREAD

**Issue by dedmen** [acemod/language-arma-atom#81]
Function autocomplete/Info for CBA_Settings_\* functions is missing.
For example CBA_Settings_init;

**Comment by thojkooi** [comment]
Thanks. 

We need to regenerate the CBA auto-complete files.

**Comment by jonpas** [comment]
No, CBA doesn't include those functions in their documentation, it's a problem on CBA side.
https://cbateam.github.io/CBA_A3/docs/index/Functions.html

I already informed @commy2 about it, as state machine ones are there.
