### ISSUE TITLE
Highlighting editing.

### ISSUE THREAD

**Issue by ghost** [acemod/language-arma-atom#86]
Where should i add them to get some worlds highlighted  as commands for example ?
(guies question general (not only to the package), but would really appreciate help)

**Comment by jonpas** [comment]
https://github.com/acemod/language-arma-atom/blob/master/grammars/sqf.json contains all definitions for highlighting.

What commands are you missing? I will be updating the definitions and releasing an update (we have fetch scripts for that).

**Comment by irvnriir** [comment]
Would be great to get all keynames for autocompletion (not only commands: event handlers, types, possibly even default animations names)
