### ISSUE TITLE
TextEditor.scrollToBottom is deprecated

### ISSUE THREAD

**Issue by SGTGunner** [acemod/language-arma-atom#92]
This is now a view method. Call TextEditorElement::scrollToTop instead.
```
TextEditor.scrollToBottom (<embedded>:5427:18)
<unknown> (C:\Users\campb\.atom\packages\language-arma-atom\lib\open-latest-rpt-file.coffee:32:17)
```

**Comment by jonpas** [comment]
I am a bit confused by this, it is used as a view method, and calling `scrollToTop()` is the opposite of what we want.

**Comment by ShadowRanger** [comment]
This has been fixed in the latest version. https://github.com/acemod/language-arma-atom/commit/a6422c59bceae77e4bd5664da3d503eab4d75699
